// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Background } from "@/components/landing-page/Background"; // Import it here

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Video Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#030014] text-white`}>
        {/* MOUNT THE BACKGROUND HERE */}
        <Background />
        
        {/* All your other components render on top of it */}
        <main className="relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}